services:
  - type: web
    name: devtools
    env: node
    buildCommand: npm install -g @angular/cli && npm install @angular-devkit/build-angular && npm install && ng build --configuration production
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true 