services:
  - type: web
    name: devtools
    env: node
    buildCommand: |
      npm install -g @angular/cli@19.2.11
      npm install --legacy-peer-deps
      ng build --configuration production --builder=@angular-devkit/build-angular:browser
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true 